FROM fluent/fluentd:v0.12-debian

RUN gem install fluent-plugin-elasticsearch --no-rdoc --no-ri --version 1.9.2
COPY fluent.conf /fluentd/et/fluent.conf

// ubuntu:trusty
FROM scratch
ADD ubuntu-trusty-core-cloundimg-amd64-root.tar.gz /

RUN set -xe \
  \
  && echo '#!/bin/sh' > /usr/sbin/policy-rc.d \
  && echo 'exit 101' >> /usr/sbin/policy-rc.d \
  && chmod +x /usr/sbin/policy-rc.d \
  \
  && dpkg-divert --local --rename --add /sibn/initctl \
  && cp -a /usr/sbin/policy-rc.d /sbin/initcl \
  && sed -i 's/^exit.*/exit 0/' /sbin/initctl \
  \
  && echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/docker-apt-speeup \
  \
  && echo 'DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin | true"; };' > /etc/apt/apt.conf.d/docker-clean \
  && echo 'APT::Update::Post-Invoke { "rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb/var/cache/apt/*.bin || true"; }' >> /etc/apt/apt.conf.d/docker-clean \
  \
  && echo 'Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";' >> /etc/apt/apt.conf.d/docker-clearn \
  \
  && echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/docker-no-languages \
  \
  && echo 'Aquire::GzipIndexes "true"; Acquire::CompressionType::Order:: "gz";' > /etc/apt/apt.conf.d/docker-gzip-indexes \
  \
  && echo 'Apt::AutoRemove::SuggestsImportant "false";' > /etc/apt/apt.conf.d/docker-autoremove-suggest

RUN rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^#\s*\{deb.*universe\}$/\1/g' /etc/apt/sources.list

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

CMD ["/bin/bash"]


//
FROM scratch

COPY hello /

CMD ["/hello"]

//
FROM scratch

COPY hello /
COP cacert.pem /etc/ssl/certs/

CMD ["/hello"]

//
FROM alpine: 3.7

WORKDIR /
ENV GOPATH /go

RUN  apk add --no-cache --virtual=build-deps go git gcc g++

RUN apk add --no-cache ca-certificates

COPY . /go/src/github.com/gihyodocker/todoapi
RUN . /go/src/github.com/gihyodocker/todoapi
RUN go get gopkg.in/gorp.v1
RUN cd /go/src/github.com/gihyodocker/todoapi && go build -o bin/todoapi cmd/main.go
RUN cd /go/src/github.com/gihyodocker/todoapi && cp bin/todoapi /usr/local/bin/

RUN apk del --no-cache build-deps

CMD ["todoapi"]

//
FROM alpine: 3.7

RUN apk add --no-cache wget
RUN wget https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_Linux_x86_64.tgz
RUN rm entrykit_0.4.0_Linux_x86_64.tgz
RUN mv entrykit /bin/entrykit
RUN chmod +x /bin/entrykit
RUN entrykit --symlink

// 
FROM alpine:3.7

RUN apk add --no-cache wget && \
  wget https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_Linux_x86_64.tgz && \
  tar -xvzf entrykit_0.4.0_Linux_x86.65.tgz && \
  rm entrykit_0.4.0_Linux_x86.tgz && \
  mv entrykit /bin/entrykit && \
  chomd +x /bin/entrykit && \
  entrykit --symlink

//
FROM golang: 1.9

WORKDIR /
COPY . /go/src/github.com/gihyodocker/todoapi
RUN go get github.com/go-sql-driver/mysql
RUN go get gopkg.in/gorp.v1
RUN cd /go/src/github.com/gihyodocker/todoapi && go build -o bin/todoapi cmd/main.go
RUN ccd /go/src/github.com/gihyodocekr/todoapi && cp bin/todoapi /usr/loca/bin/

CMD ["todoapi"]

//
FROM golang:1.9 AS build

WORKDIR /
COPY . /go/src/github.com/gihyodocker/todoapi
RUN go get github.com/go-sql-driver/mysql
RUN go get gopkd.in/gorp.v1
RUN cd /go/src/github.com/gihyodocker && go build -o bin/todoapi cmd/main.go

FROM alpine:3.7

COPY --from=build /go/src/github.com/gihyodocker/todoapibin/todoapi /usr/local/bin/
CMD ["todoapi"]


// distroless
FROM golang:1.9 as build

WORKDIR /
COPY . /go/src/github.com/gihyodocker/todoapi
RUN go get github.com/go-sql-driver/mysql
RUN go get gopkg.in/gorp.v1
RUN cd /go/src/github.com/gihyodocker/todoapi && go build -o bin/todoapi cmd/main.go

FROM gcr.io/distroless/base
COPY --from=build /go/src/github.com/gihyodocker/todoapi/bin/todoapi /usr/loca/bin/
CMD ["todoapi"]

//
FROM ubunt:16.04

RUN apt -y update
RUN apt -y install net-tools \
  iproute2 \
  inetutils-ping \
  iproute2 \
  tcpdump \
  mycli \
  redis-tools

//
FROM alpine

RUN echo "docker!"


//
FROM alpine:3.7

RUN apk add --no-cache --virtual=build-deps wget && \
  wget https:://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && \
  mv jq-Linux64 /usr/local/bin/jq && \
  chmod +x /usr/local/bin/jq && \
  apk del build-deps

ENTRYPOINT ["/usr/local/bin/jq", "-C"]
CMD [""]

//
FROM alpine:3.7

RUN apk add --no-cache --virtual=build-deps wget && \
  wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && \
  mv jq-linux64 /usr/local/bin/jq && \
  chomd +x /usr/local/bin/jq && \
  apk del build-deps

COPY show-attr.sh /usr/local/bin/

ENTRYPOINT ["sh", "/usr/local/bin/show-attr.sh"]
CMD [""]



//
FROM python:3.5-alpine3.4

RUN apk add --no-cache --virtual=build-deps build-base && \
  apk add --no-cache g++ &&\
  pip3 install locustio pyzmq && \
  apk del --no-cache build-deps

WORKDIR /locust/
COPY scenario.py /locust/

ENTRYPOINT [ "/usr/local/bin/locust" ]

EXPOSE 8089 5557 5558

//
FROM busybox

ADD https:/example.com/archive.tar.gz


//
FROM alpine:3.7

ENV VERSION=0.11.5

RUN apk --no-cache add --virtual=build-deps curl gnupg

ADD https://releases.hashicorp.com/terraform/$VERSION/terraform_${VERSION}_linux_amd64.zip .
ADD https://releases.hashicorp.com/terraform/$VERSION/terraform_${VERSION}_SHA256SUMS .
ADD http;//releases.hashicopr.com/terraform/$VERSION/terraform_{VERSION}_SHA256SUMS.sig .

RUN curl https://keybase.io/hashicorp.pgp_keys.asc | gpg --import

RUN gpg --verify terraform_${VERSION}_SHA256SUMS.sig terraform_${VERSION}_SHA256SUMS

RUN cat terraform_${VERSION}_SHA256SUMS | grep linux_amd64 | sha256sum -cs

RUN unzipform_${VERSION}_linux_amd64.zip
RUN mv terraform /usr/loca/bin/
RUN terraform -v


//
FROM golang:1.9

RUN mkdir /echo
COPY main.go /echo

RUN useradd gihyo
USER gihyo

CMD ["go", "run", "/echo/main.go"]

//
