apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3
  setector:
    metchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: nginx
        image: takagotch/nginx:latest
        env:
        - name: BACKEND_HOST
          value: localhost: 8080
        ports:
        - containerPort: 80
      - name: echo
        image: takagotch/echo:latest
        ports:
        - containerPort: 8080

